lib/slash_server_web/router.ex
defmodule SlashServerWeb.Router do
  use SlashServerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SlashServerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :session_auth do
    plug SlashServerWeb.Plugs.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SlashServerWeb do
    pipe_through :browser

    get "/", AuthController, :show
    post "/", AuthController, :login
  end

  scope "/commands", SlashServerWeb do
    pipe_through :browser
    pipe_through :session_auth

    #Command Group
    get "/", CommandGroupController, :show
    get "/new", CommandGroupController, :new
    get "/:name/edit", CommandGroupController, :edit

    post "/delete/:name", CommandGroupController, :delete
    post "/new", CommandGroupController, :create_or_update

    #Command
    get "/:command_group", CommandController, :show
    get "/:command_group/new", CommandController, :new
    get "/:command_group/:name/edit", CommandController, :edit

    post "/:command_group/new", CommandController, :create_or_update
    post "/:command_group/delete/:name", CommandController, :delete
  end

  scope "/slash", SlashServerWeb do
    pipe_through :api

    post "/", SlashController, :slash
  end

  # Other scopes may use custom stacks.
  # scope "/api", SlashServerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SlashServerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/slash_server/resources/command.ex
defmodule SlashServer.Command do
  use Ash.Resource, data_layer: AshPostgres.DataLayer

  postgres do
    repo SlashServer.Repo
    table "command"
  end

  attributes do
    uuid_primary_key :command_id

    attribute :name, :string,
      allow_nil?: false,
      constraints: [
        max_length: 100,
        match: ~r/^([a-z])+-?([a-z])+$/i
      ]

    attribute :description, :string do
      allow_nil? false
      constraints max_length: 100
    end

    attribute :response, :string do
      allow_nil? false
      constraints max_length: 2000
    end

    # This is set on create
    create_timestamp :inserted_at
    # This is updated on all updates
    update_timestamp :updated_at
  end

  identities do
    identity :unique_name, [:name]
  end

  relationships do
    belongs_to :command_group, SlashServer.CommandGroup
  end

  actions do
    create :create
    read :read
    update :update
    destroy :destroy
  end
end

lib/slash_server_web/controllers/command_controller.ex
defmodule SlashServerWeb.CommandController do
  use SlashServerWeb, :controller

  def show(conn, %{"command_group" => command_group}) do
    case SlashServer.Api.get!(SlashServer.CommandGroup, name: command_group)
         |> SlashServer.Api.load([:commands]) do
      {:ok, %SlashServer.CommandGroup{commands: commands}} ->
        case commands do
          %Ash.NotLoaded{} ->
            render(conn, "show.html", names: [], command_group: command_group)

          _ ->
            names = Enum.map(commands, fn c -> Map.get(c, :name) end)
            render(conn, "show.html", names: names, command_group: command_group)
        end

      _ ->
        render(conn, "show.html", names: [], command_group: command_group)
    end
  end

  def new(conn, %{"command_group" => command_group}) do
    render(conn, "new.html",
      name: nil,
      description: nil,
      response: nil,
      command_group: command_group
    )
  end

  def edit(conn, %{"name" => name, "command_group" => command_group}) do
    if name != nil do
      case SlashServer.Api.get(SlashServer.Command, name: name) do
        {:ok, res} ->
          %{name: name, description: desc, response: resp} = res

          conn
          |> assign(:edit, true)
          |> render("new.html",
            name: name,
            description: desc,
            response: resp,
            command_group: command_group
          )

        _ ->
          render(conn, "new.html", name: nil, description: nil, command_group: command_group)
      end
    else
      render(conn, "new.html", name: nil, description: nil, command_group: command_group)
    end
  end

  def create_or_update(conn, %{"command" => command_data, "command_group" => command_group}) do
    %{"name" => name, "description" => desc, "response" => resp} = command_data

    case SlashServer.Api.get!(SlashServer.CommandGroup, name: command_group)
         |> SlashServer.Api.load([:commands]) do
      {:ok, group} ->
        res =
          case SlashServer.Api.get(SlashServer.Command, name: name) do
            {:ok, res} ->
              Ash.Changeset.for_update(res, :update, command_data)
              |> SlashServer.Api.update()

              SlashServer.Api.load!(group, [:commands])

            _ ->
              {:ok, command} =
                Ash.Changeset.for_create(SlashServer.Command, :create, command_data)
                |> SlashServer.Api.create()

              group
              |> SlashServer.Api.load!([:commands])
              |> Ash.Changeset.for_update(:update)
              |> Ash.Changeset.replace_relationship(:commands, [command | group.commands])
              |> SlashServer.Api.update()
              |> SlashServer.Api.load!([:commands])
          end

        case res do
          {:error, _command} ->
            conn
            |> put_flash(:error, "Invalid entry")
            |> render("new.html",
              name: name,
              description: desc,
              response: resp,
              command_group: command_group
            )

          _ ->
            IO.inspect(res)

            commands =
              Enum.map(res.commands, fn c -> %{name: c.name, description: c.description} end)

            SlashServer.Discord.create_command(group.name, group.description, commands)
            redirect(conn, to: Routes.command_path(conn, :show, command_group))
        end

      _ ->
        conn
        |> put_flash(:error, "Command group does not exist")
        |> render("new.html",
          name: name,
          description: desc,
          response: resp,
          command_group: command_group
        )
    end
  end

  def delete(conn, %{"name" => name, "command_group" => command_group}) do
    case SlashServer.Api.get(SlashServer.Command, name: name) do
      {:ok, res} ->
        case Ash.Changeset.for_destroy(res, :destroy)
             |> SlashServer.Api.destroy()
             |> IO.inspect() do
          :ok ->
            %{name: name, description: desc, commands: commands} =
              SlashServer.CommandGroup
              |> SlashServer.Api.get!(name: command_group)
              |> SlashServer.Api.load!([:commands])

            SlashServer.Discord.create_command(name, desc, commands)
            redirect(conn, to: Routes.command_path(conn, :show, command_group))

          _ ->
            conn
            |> put_flash(:error, "Could not delete command")
            |> redirect(to: Routes.command_path(conn, :show, command_group))
        end

      _ ->
        conn
        |> put_flash(:error, "Could not delete command")
        |> redirect(to: Routes.command_path(conn, :show, command_group))
    end
  end
end

lib/slash_server_web/views/command_view.ex
defmodule SlashServerWeb.CommandView do
  use SlashServerWeb, :view
end

lib/slash_server_web/templates/command/new.html.heex
<section class="w-10/12 flex flex-col justify-center items-center py-6">

  <%= form_for @conn, Routes.command_path(@conn, :create_or_update, @command_group), [as: :command, class: "flex flex-col w-full gap-2"], fn f -> %>
    <label class="flex flex-col">
      <div>Name</div>
        <%=
          readonly? = if assigns[:edit] do
            true
          else
            false
          end

          text_input f, :name, [class: "border border-black pl-2", readonly: readonly?, value: @name] 
        %>
    </label>
    
    <label class="flex flex-col">
      Description <%= text_input f, :description, [class: "border border-black pl-2", value: @description] %>
    </label>
    
    <label class="flex flex-col">
      Response <%= textarea f, :response, [class: "border border-black resize-none px-2", rows: "10", value: @response] %>
    </label>
    <%= submit "Create", [class: "self-start border border-black cursor-pointer mt-2 px-2"] %>
  <% end %>
</section>

lib/slash_server_web/templates/command/show.html.heex
<section class="w-4/5 flex py-6 flex-col justify-center items-center gap-4">
  <h1 class="self-start text-2xl">/<%= @command_group %></h1>
  <div class="flex justify-start self-start font-bold text-blue-600 underline">
      &#60;- <%= link "Command Groups", to: Routes.command_group_path(@conn, :show) %>
  </div>
  <div class="flex flex-col divide-y-2 divide-black w-full min-h-16 border border-black px-3 py-2">
    <%= if @names == [] do%>
      No commands
    <% else %>
      <%= for name <- @names  do %>
        <div class="flex flex-row justify-between gap-5 w-full py-4">
          <div>
            <%= name %>
          </div>
          <div class="flex flex-row gap-4">
            <div class="border border-black px-4">
              <a href={Routes.command_path(@conn, :edit, @command_group, name)}>Edit</a>
            </div>
            <div>
              <%= form_for @conn, Routes.command_path(@conn, :delete, @command_group, name), [as: :command, class: "flex flex-col w-full"], fn _f -> %>
                <%= submit "Delete", [class: "border border-black px-2"] %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="flex flex-row justify-start self-start border border-black px-2 cursor-pointer">
    <a href={Routes.command_path(@conn, :new, @command_group)} class="cursor-pointer">New</a>
  </div>
</section>